#include "std.h"

void basic_link(void (*rtSym)(std::string sym))
{
    rtSym("_bbIntType");
    rtSym("_bbFltType");
    rtSym("_bbStrType");
    rtSym("_bbCStrType");

    rtSym("_bbStrLoad");
    rtSym("_bbStrRelease");
    rtSym("_bbStrStore");
    rtSym("_bbStrCompare");
    rtSym("_bbStrConcat");
    rtSym("_bbStrToInt");
    rtSym("_bbStrFromInt");
    rtSym("_bbStrToFloat");
    rtSym("_bbStrFromFloat");
    rtSym("_bbStrConst");
    rtSym("_bbDimArray");
    rtSym("_bbUndimArray");
    rtSym("_bbArrayBoundsEx");
    rtSym("_bbVecAlloc");
    rtSym("_bbVecFree");
    rtSym("_bbVecBoundsEx");
    rtSym("_bbObjNew");
    rtSym("_bbObjDelete");
    rtSym("_bbObjDeleteEach");
    rtSym("_bbObjRelease");
    rtSym("_bbObjStore");
    rtSym("_bbObjCompare");
    rtSym("_bbObjNext");
    rtSym("_bbObjPrev");
    rtSym("_bbObjFirst");
    rtSym("_bbObjLast");
    rtSym("_bbObjInsBefore");
    rtSym("_bbObjInsAfter");
    rtSym("_bbObjEachFirst");
    rtSym("_bbObjEachNext");
    rtSym("_bbObjEachFirst2");
    rtSym("_bbObjEachNext2");
    rtSym("_bbObjToStr");
    rtSym("_bbObjToHandle");
    rtSym("_bbObjFromHandle");
    rtSym("_bbNullObjEx");
    rtSym("_bbRestore");
    rtSym("_bbReadInt");
    rtSym("_bbReadFloat");
    rtSym("_bbReadStr");
    rtSym("_bbAbs");
    rtSym("_bbSgn");
    rtSym("_bbMod");
    rtSym("_bbFAbs");
    rtSym("_bbFSgn");
    rtSym("_bbFMod");
    rtSym("_bbFPow");
    rtSym("RuntimeStats");
}
